server:
  port: 3010
  servlet:
    context-path: /api/alan

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_name
    username: root
    password: .......
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: false
        show-sql: true
    hibernate:
      ddl-auto: update